name: MP4 TO GIF

on: workflow_dispatch

jobs:
  sending:
    runs-on: ubuntu-latest
    steps:
      - name: Make a Gif
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - uses: LeGitHubDeTai/mp4TOgif@main
        env:
         inMP4: './video.mp4'
         outGIF: './out.gif'
      - run: sudo apt update
      - run: sudo apt install ffmpeg
